# -*- coding: utf-8 -*-
"""(Bharathi) HW6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tivxeFP9agAn8XExlRSp4Gl8UWEEo-UV
"""

import pandas as pd
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

"""##Q3
Please follow the instructions below and inspect the outputs before you proceed. You can always check this original final to compare your results in your own copy.
"""

#You have to make sure that you were able to write the file to a csv while your were working in R
house=pd.read_csv('/content/drive/MyDrive/DATA/house_prices.csv')
house.head()

"""a) For the states below, please select the rows from the house dataframe, and consider converting the date column to date data type as it may be coming in string format. Then use the head function to preview your new dataframe."""

states = ['Michigan', 'California', 'Texas', 'Indiana']
#your code goes here
house['date'] = pd.to_datetime(house['date'])
house_states = house[house['state'].isin(states)]
house_states.head()

"""b) Use the FacetGrid from seaborn to create line plots to represent house_price_index for each state. Please make the line color red, set ticks on x axis for years ['1980', '2000', '2020'], which you may have to convert date type again, put those years as labels, and set the titles for each small plot to their state names. In addition, set the y label to 'house price index' and remove the x label since it's obvious that these are years."""

#your code goes here
import matplotlib.pyplot as plt

house_states['year'] = house_states['date'].dt.year
house_states = house_states.sort_values(by='date')

g = sns.FacetGrid(house_states, col="state", col_wrap=4, sharey=False, height=4)

# Map lineplot to each facet
g.map_dataframe(sns.lineplot, x="date", y="house_price_index", color='red')

# Customize each subplot
for ax in g.axes.flat:
    ax.set_xticks(pd.to_datetime(['1980', '2000', '2020']))
    ax.set_xticklabels(['1980', '2000', '2020'])
    ax.set_xlabel('')  # Remove x-axis label


g.set_ylabels("house price index")

g.set_titles(col_template="{col_name}")

# Tight layout
plt.tight_layout()
plt.show()

"""c) Draw a lineplot for 'house price perc', but color them based on the 'state' name which will have four lines in a single plot. Set a legend which will be at the bottom of your graph and have them horizantally positioned next to eachother. Again, set the y label to house_price_perc and remove the x label since it's obvious. (Note that my y label is still showing index. Please ignore that.)"""

#your code goes here
sns.set(style="whitegrid")

plt.figure(figsize=(10, 6))
sns.lineplot(data=house_states, x='date', y='house_price_perc', hue='state', palette='Set1')
plt.xlabel('')
plt.ylabel('house_price_perc')
plt.legend(loc='lower center', ncol=4, bbox_to_anchor=(0.5, -0.2))
plt.tight_layout()
plt.show()

"""##Q4
Please work on your 4th question below. Please feel free to add new code cells.
"""

#Your code goes here.
world_cup = pd.read_csv('/content/drive/MyDrive/DATA/WorldCupMatches.csv')
world_cup.head()

#your code goes here. Just leaving an example output of an intermediate step for you to check the last two columns
#A hint to start with: team_pairs = world_cup.groupby(['Home Team Initials', 'Away Team Initials']).count().reset_index()
team_pairs = world_cup.groupby(['Home Team Initials', 'Away Team Initials']).size().reset_index(name = 'weight')
team_pairs.head()

"""Make sure that you only write four columns ('Home Team Initials', 'Away Team Initials', 'weight', 'HomeGoalTotal') from the data frame, team_pairs, to a csv file"""

#part(b)
HomeGoalTotal = world_cup.groupby(['Home Team Initials','Away Team Initials'])['Home Team Goals'].sum().reset_index (name = 'HomeGoalTotal')
HomeGoalTotal.head()

#part(c)
team_pairs = pd.merge(team_pairs, HomeGoalTotal, on=['Home Team Initials', 'Away Team Initials'], how='left')
team_pairs.head()

#part(d)
team_pairs.to_csv('team_pairs.csv', index = False)
print(team_pairs)